# Generated by Django 5.2.8 on 2025-11-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefData',
            fields=[
                ('video_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='视频ID')),
                ('theme', models.CharField(choices=[('animals_and_ecology', '动物与生态'), ('architecture', '建筑'), ('commercial_marketing', '商业营销'), ('food', '食物'), ('industrial_activity', '工业活动'), ('landscape', '风景'), ('people_daily', '人物日常'), ('sports_competition', '体育竞技'), ('transportation', '交通')], max_length=50, verbose_name='主题类型')),
                ('shot_type', models.CharField(choices=[('single', '单镜头'), ('multi', '多镜头')], max_length=10, verbose_name='镜头类型')),
                ('prompt', models.TextField(verbose_name='Prompt描述')),
                ('video_file', models.FileField(upload_to='refdata/videos/', verbose_name='视频文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '参考数据',
                'verbose_name_plural': '参考数据',
                'db_table': 'refdata',
            },
        ),
        migrations.CreateModel(
            name='GenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100, verbose_name='视频ID')),
                ('theme', models.CharField(choices=[('animals_and_ecology', '动物与生态'), ('architecture', '建筑'), ('commercial_marketing', '商业营销'), ('food', '食物'), ('industrial_activity', '工业活动'), ('landscape', '风景'), ('people_daily', '人物日常'), ('sports_competition', '体育竞技'), ('transportation', '交通')], max_length=50, verbose_name='主题类型')),
                ('shot_type', models.CharField(choices=[('single', '单镜头'), ('multi', '多镜头')], max_length=10, verbose_name='镜头类型')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('prompt', models.TextField(verbose_name='Prompt描述')),
                ('video_file', models.FileField(upload_to='gendata/videos/', verbose_name='视频文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '生成数据',
                'verbose_name_plural': '生成数据',
                'db_table': 'gendata',
                'indexes': [models.Index(fields=['model_name'], name='gendata_model_n_8b1a9a_idx')],
            },
        ),
    ]
