# Generated by Django 5.2.8 on 2026-01-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ref_data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenData',
        ),
        migrations.AlterField(
            model_name='refdata',
            name='video_file',
            field=models.CharField(max_length=500, verbose_name='视频文件路径'),
        ),
    ]
