encoder:
  # 建议指向本地目录以避免网络波动
  model_name_or_path: /root/autodl-tmp/Ref4D-VideoBench/checkpoints/e5-large-v2
  device: cuda          # 或 cpu
  dtype: bf16           # bf16/fp16/fp32
  batch_size: 128
  max_length_query: 64
  max_length_passage: 128
  query_prefix: "query: "
  passage_prefix: "passage: "
  normalize: true
  cache_dir:
  local_files_only: false
  revision:
  trust_remote_code: false

preprocess:
  lowercase: true
  strip: true
  collapse_spaces: true
  unify_hyphen_underscore: true
  remove_quotes: true
  remove_decorations: true
  drop_if_no_alpha: true
  max_value_len: 64

repr:
  use_name_channel: true
  use_set_channel: true
  pooling: weighted_mean        # mean / weighted_mean
  name_weight: 1.0
  key_weight:
    # —— 提升权重的结构键 ——
    signature: 2.0
    pattern: 1.7
    pose: 1.7
    state: 1.7
    position: 1.5
    color: 1.5
    
    # —— 全量 facets：默认 1.0（如未显式配置会在装载时回填）——
    texture: 1.3
    material: 1.3
    size: 1.3
    age: 1.3
    sex: 1.3
    action: 1.3
    orientation: 1.0
    facing-direction: 1.0
    object-part: 1.0
    tool-or-instrument: 1.0
    equipment: 1.0
    species-or-breed: 1.3
    vehicle-type: 1.0
    food-type: 1.3
    art-medium: 1.0
    style: 1.0
    weather: 1.0
    lighting: 1.0
    scene: 1.0
    camera-view: 1.0
    printed-text: 1.0
    brand-or-logo: 1.0
    number-or-id: 1.0

sim:
  tau0: 0.5          # 负对分位线；会被映射到 [0,1] 的核使用
  combine: weighted        # name/set 通道融合：max 或weighted
  w_name: 0.4          # 双通道加权：名称通道权重
  w_set: 0.6           # 集合通道（属性集合）权重
  gate_min: 0.60       # 建议 0.55–0.65

matching:
  algo: hungarian
  min_gate: 0.6      # 与 sim.gate_min 取最大值生效

fusion:
  alpha: 0.30
  beta: 0.40
  gamma: 0.30
