# Generated by Django 5.2.8 on 2025-12-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('user_email', models.EmailField(max_length=255, verbose_name='提交用户邮箱')),
                ('username', models.CharField(max_length=150, verbose_name='提交用户名')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('api_url', models.URLField(max_length=500, verbose_name='API地址')),
                ('api_key', models.CharField(max_length=500, verbose_name='API密钥')),
                ('description', models.TextField(blank=True, verbose_name='模型简介')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='发布者')),
                ('parameters', models.CharField(blank=True, max_length=100, verbose_name='参数规模')),
                ('is_open_source', models.BooleanField(default=False, verbose_name='是否开源')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='发布时间')),
                ('official_website', models.URLField(blank=True, max_length=500, verbose_name='官网链接')),
                ('status', models.CharField(choices=[('pending', '等待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='任务状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('message', models.TextField(blank=True, verbose_name='状态消息')),
                ('semantic_score', models.FloatField(blank=True, null=True, verbose_name='语义一致性评分')),
                ('temporal_score', models.FloatField(blank=True, null=True, verbose_name='时序一致性评分')),
                ('motion_score', models.FloatField(blank=True, null=True, verbose_name='运动属性评分')),
                ('reality_score', models.FloatField(blank=True, null=True, verbose_name='真实性评分')),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='总分')),
                ('model_id', models.IntegerField(blank=True, null=True, verbose_name='关联模型ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '评测任务',
                'verbose_name_plural': '评测任务列表',
                'db_table': 'task_list',
                'ordering': ['-created_at'],
            },
        ),
    ]
