# Generated by Django 5.2.8 on 2025-12-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='激活令牌'),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_token_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='激活令牌创建时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='是否为员工'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='是否为超级用户'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='密码重置验证码'),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_token_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='重置令牌创建时间'),
        ),
    ]
