# Generated by Django 5.2.8 on 2025-12-03 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_activation_token_user_activation_token_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
